### ISSUE TITLE
Error in Saved models 

### ISSUE THREAD

**Issue by RollerCoaster1899** [knu-lcbc/MolForge#2]
When trying to use the ECFP4 to SMILES and using the example the following error appears.

[Test-MolForge.ipynb - Colaboratory.pdf](https://github.com/knu-lcbc/MolForge/files/11784024/Test-MolForge.ipynb.-.Colaboratory.pdf)
`%cd /content/drive/MyDrive/Github/
!git clone https://github.com/knu-lcbc/MolForge.git
%cd /content/drive/MyDrive/Github/MolForge/
!pip install virtualenv
!virtualenv MolForge_env
!source MolForge_env/bin/activate
!pip install -r environment.yml
!pip install .

!python predict.py --fp='ECFP4' --model_type='smiles' --input='1 80 94 114 237 241 255 294 392 411 425 695 743 747 786 875 1057 1171 1238 1365 1380 1452 1544 1750 1773 1853 1873 1970'`

It outputs: 
2.0.1+cu118
Traceback (most recent call last):
  File "/content/drive/MyDrive/Github/MolForge/predict.py", line 6, in <module>
    main()
  File "/content/drive/MyDrive/Github/MolForge/MolForge/predict.py", line 108, in main
    assert os.path.exists(f"{args.checkpoint}"), f"There is no checkpoint {args.checkpoint} in the saved_models."
AssertionError: There is no checkpoint /content/drive/MyDrive/Github/MolForge/saved_models/ECFP4_smiles_checkpoint.pth in the saved_models.

**Comment by ashyrmamatov01** [comment]
It looks like there's a problem - the checkpoint file can't be found in the `MolForge/saved_models/` directory, based on the error message

It is expected that the checkpoint files should be located in  the  `MolForge/saved_models/` directory (see [Example](https://github.com/knu-lcbc/MolForge/blob/main/README.md#prediction--demo)). 

Could you please make sure that the checkpoint files ([top-performing](https://drive.google.com/uc?id=1zl6HBdwYsnA4JcnOi1o6OmcrRDB5iySK) or [all the oher models](https://drive.google.com/uc?id=1jCtbc9lMacCyiZ3iZFEtFgOfOQYtWEuD)) are downloaded and unzipped into the `MolForge/saved_models/` directory?

If the error still persists, please let us know. 

**[UPDATED]**
You could also set the name of checkpoint file explicitly with `--checkpoint` argument in `predict.py` script. Note that `--checkpoint` argument expects to be the **name** (not a path) of checkpoint file in the `MolForge/saved_models/` directory

**Comment by RollerCoaster1899** [comment]
Thank you, Sir. Seeing the size of the models I suspect they weren't downloaded as there wasn't enough space available,

Thank you
